version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: voidbank
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - voidbank-net

volumes:
  mysql_data:

networks:
  voidbank-net: